before_script:
  - docker info

build_image:
  tags:
    - linux
    - docker  
  
  stage: build
  
  script:
    - docker build --build-arg "$HTTP_PROXY" --build-arg "$HTTPS_PROXY" -t automotive_standard_compliance .
 #   - docker run my-docker-image /script/to/run/tests